### ISSUE TITLE
[feature][UI] Voice audio source quick toggle switch

### ISSUE THREAD

**Issue by KWB** [swift-project/pilotclient#21] opened 2020-06-07 21:37 UTC
Pilots regularly want to either get up for a few minutes to do things around the vicinity of their computers/cockpits or wish to take off their headsets during longer flights. At the same time they wish to keep monitoring voice communications on active ATC-frequencies or on UNICOM, just like in the real world where we only have to wear our headsets below 10,000ft and may remove them and switch to SPEAKERS above that altitude.

Therefore it would be really, really cool if swiftGUI had the possibility of configuring "secondary audio IN and OUT devices" ("IN" should be allowed to be the same as the primary audio IN device) for such purpose and provide a "SPEAKER" toggle-button, a hotkey-definition for it and a SPEAKER status-light on the GUI. When the SPEAKER toggle-button is selected, swift will switch from its primary voice out/in devices to the secondary out/in devices and vice versa, if selected again. This could be really useful to a lot of users.

**Comment by ltoenning** [comment] 2024-03-15 21:16
Duplicate of #157

**Closed by ltoenning** 2024-03-15 21:16 UTC
Labels: enhancement
