### ISSUE TITLE
[feature][UI] Function to quickly change between audio output devices

### ISSUE THREAD

**Issue by KWB** [swift-project/pilotclient#1] opened 2020-06-07 18:19 UTC
Originally: https://dev.swift-project.org/T439

It would be really cool to have a function that allows the user to quickly change between his two favourite audio OUTPUT devices. This could be handy if a pilot needs to get up from his cockpit, but will stay in the vicinity of his computer and still wants to monitor the radio in case that ATC calls him.

Maybe a good location would be on top of the GUI, next to the status-lights. This way it would be always available, no matter what subpage the user is currently in. On the Audio page the user will be able to nominate the two audio output devices that will be affected by this click-spot.

**Comment by ltoenning** [comment] 2024-03-15 21:17
Duplicate of #157

**Closed by ltoenning** 2024-03-15 21:17 UTC
Labels: duplicate, enhancement
