### ISSUE TITLE
Mac OS Sequoia 15.2 / X-plane 11 / Swift 0.15.35 -- microphone not working 

### ISSUE THREAD

**Issue by nola504-4now** [swift-project/pilotclient#326] opened 2024-12-26 23:42 UTC
Hello,

I'm running the above config from a new Macbook Pro M4 Pro.  I've given Swift access to the internal microphone and tried Airpods as well, but Swift is not able to pick up any sound from my microphone(s).  It seems like there may be a bug per this FAQ link: https://swift-project.org/troubleshooting/no_sound_macos/

Please advise if there is a work around for this issue. 

thank you.

**Comment by nola504-4now** [comment] 2024-12-27 02:22
I tried the tssutil reset Microphone and once I restarted Swift it asked to allow mic access... but still not workings

**Comment by ltoenning** [comment] 2024-12-30 11:45
Duplicate of #316. Currently I cannot fully reproduce this but it is under investigation.

**Closed by ltoenning** 2024-12-30 11:45 UTC
Labels: duplicate
